// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Petstore
A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
    Host: petstore.swagger.io
    BasePath: /api
    Version: 1.0.0
    License: Apache 2.0 https://www.apache.org/licenses/LICENSE-2.0.html
    Contact: Swagger API Team<apiteam@swagger.io> http://swagger.io

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
